config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: {registrations: "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end

  devise_scope :user do
    get 'signup', to: 'devise/registrations#new'
  end

  resources :posts

  resources :comments

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    belongs_to :channel
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    @comment.parent_id = 0
    @comment.save
    post = Post.find(@comment.post)
    redirect_to post
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @replies = Comment.all
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = 1
    @post.channel_id = 1
    if @post.save
      redirect_to @post
    else
      redirect_to new_post_path
    end
  end

  private
  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:name,
                                    :email,
                                    :password,
                                    :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:name,
                                    :email,
                                    :password,
                                    :password_confirmation,
                                    :current_password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
    def comment_tree(@comment)
        children = Comment.where(parent_id: @comment.id)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chaos!</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav>
    <div class="brand">
      <%= image_tag "logo.svg" %>
    </div>
    <div class="centered-nav">
      <ul>
        <li>Home</li>
        <li>Popular</li>
        <li>All</li>
        <li>Random</li>
        <li>Users</li>
        <li>Channels</li>
      </ul>
    </div>
    <div class="profile-thumbnail">
      <% if user_signed_in? %>
        <p>
          <%= current_user.name %>
          <a href="<%= new_post_path %>">New Post</a>
        </p>
      <% else # user not signed in %>
        <p>
          <a href="<%= login_path %> ">Login</a>|<a href="<%= signup_path %>">Sign Up</a>
        </p>
      <% end %>
    </div>
  </nav>

  <div class="main-content">
    <%= yield %>
  </div>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<div class="sidenav">
  <ul>
    <li>
      <a href="#">Hot</a>
    </li>
    <li>
      <a href="#">New</a>
    </li>
    <li>
      <a href="#">Rising</a>
    </li>
    <li>
      <a href="#">Top</a>
    </li>
    <li>
      <a href="#">Bookmarked</a>
    </li>
  </ul>
</div>

app/views/posts/index.html.erb
<%= render 'partials/sidebar' %>

<div class="posts-container">
  <% @posts.each do |post| %>
    <div class="post">
      <h3>
        <%= link_to post.title, post_path(post.id) %>
        <span class="post_author">
          <a href="#" class="muted">
          <%= post.user.name %>
          </a>
        </span>
      </h3>
      <p>
        <%= post.content %>
      </p>
      <p class="bottom-links">
        <a href="#" class="muted">Comments</a>
        <a href="#" class="muted">Bookmark</a>
        <a href="#" class="muted">Flag</a>
        <% if user_signed_in? and (current_user.id === post.user_id) %>
          <a href="#" class="muted">Edit</a>
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h3 class="page-title">Add a new Post</h3>
<%= render partial: "posts/partials/form", locals: {post: @post} %>

app/views/posts/partials/_form.html.erb
<%= form_for(post) do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-error">
      <ul>
        <% form.object.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <%end %>
      </ul>
    </div>
  <% end %>
  <div class="form-field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="form-field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="form-field">
  <button type="submit" name="submit">Post</button>
  </div>
<% end %>

app/views/posts/show.html.erb
<div class="posts-container">
  <h2 style="margin-bottom: 8px;"><%= @post.title %></h2>
  <div class="post-body" style="padding-bottom: 16px; border-bottom: 1px solid rgba(0,0,0,0.24);">
    <%= @post.content %>
  </div>
  <div class="comment-wrapper">
    <% if user_signed_in? %>
      <%= form_for(@comment) do |form| %>
        <% if form.object.errors.any? %>
          <div class="alert alert-error">
            <ul>
              <% form.object.errors.full_messages.each do |msg| %>
                <li> <%= msg %> </li>
              <%end %>
            </ul>
          </div>
        <% end %>
        <%= hidden_field_tag "comment[user_id]", current_user.id %>
        <%= hidden_field_tag "comment[post]", @post.id %>
        <div class="form-field">
          <%= form.label :comment %>
          <%= form.text_area :comment %>
        </div>

        <div class="form-field">
          <button type="submit" name="submit">Submit</button>
        </div>
      <% end %>
    <% end %>
    <hr/>
    <% @replies.each do |reply| %>
    <div class="reply">
      <%= reply.comment %>
    </div>
    <% if comment_tree(reply).empty? %>
    <% else %>
      <div class="child">
      </div>
    <% end %>
  </div>
</div>